
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 03 02:13:52 PST 2011
//----------------------------------------------------

package jevolution.expressions;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GREEN = 3;
  public static final int LITERAL = 7;
  public static final int POWOP = 12;
  public static final int ADDOP = 8;
  public static final int EOF = 0;
  public static final int HEIGHT = 6;
  public static final int error = 1;
  public static final int RPAREN = 14;
  public static final int BLUE = 4;
  public static final int DIVOP = 11;
  public static final int MULTOP = 10;
  public static final int WIDTH = 5;
  public static final int RED = 2;
  public static final int LPAREN = 13;
  public static final int SUBOP = 9;
}

